pix2code/app1/urls.py

from django.contrib import admin
from django.urls import path
from . import views


app_name ="app1"
urlpatterns = [
    #path('upload/', views.model_form_upload, name='upload'),
    path('upload/', views.UploadView.as_view(), name='upload'),
    
]


pix2code/pix2code/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pix2code/', include('app1.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pix2code/app1/models.py
from django.db import models


class Document(models.Model):
    
    document = models.ImageField(verbose_name="File Upload", upload_to='png/')
 


pix2code/app1/forms.py

from django import forms
from .models import Document
from upload_validator import FileTypeValidator

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('document', )
    
    
    document = forms.FileField(label="File Upload",
        widget=forms.ClearableFileInput(attrs={'multiple': True}),
        validators=[FileTypeValidator(allowed_types=[ 'image/png'])])

        

pix2code/app1/views.py
from django.shortcuts import render
from django.views import generic
from .forms import DocumentForm
from .models import Document
from .utils import ScreenShot
from .config import *
from django.conf import settings
from app1.compiler.classes.Compiler import *
from keras import backend as K
import shutil
import os
import glob
import shutil, os
import glob


class UploadView(generic.FormView):
    form_class = DocumentForm
    template_name = 'app1/model_form_upload.html'

    def form_valid(self, form):
        K.clear_session()
        ss = ScreenShot()
        form.save()
        file_name = self.request.FILES['document'].name
        try:
            tokenizer =  ss.init_token()
            ss.create_gui(file_name)
            shutil.move(os.path.join(PNG_PATH, file_name), os.path.join(CODE_PATH ,file_name))
            ss.create_npz()
            file_list = glob.glob(CODE_PATH + "\\*")
            for file in file_list:
                os.remove(file)
            train_features, texts = ss.load_data()
            loaded_model, graph = ss.load_model()
            _, _, predicted = ss.evaluate_model(loaded_model, texts, train_features, tokenizer, ss.max_length, graph)
            compiler = Compiler(DSL_PATH)
            compiled_website = compiler.compile(predicted[0], TEMPLATE_HTML)
            ss.output_html(compiled_website)
            ss.remove_files(FEATUR_PATH)
            message = "Processing ended normally."
            context = {
                'message': message,
                'PREDICTED_HTML': PREDICTED_HTML,
                'compiled_website':compiled_website,}
            return render(self.request, 'app1/complete.html', context)
        except Exception as e:
            err_args ="Error:" + str(e.args)
            err_message ="message:" + str(e)
            context = {
                'err_args': err_args,
                'err_message': err_message,}
            return render(self.request, 'app1/complete.html', context)


    def form_invalid(self, form):
        return render(self.request, 'app1/model_form_upload.html', {'form': form})



pix2code/app1/templates/app1/base.html
{% load static %}
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  {# Bootstrap4を使う #}
  <!-- linkタグでbootstrapのcssファイルを読み込む -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
  <!-- linkタグでDataTableのcssファイルを読み込む -->
  <link rel="stylesheet" href="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.css"/> 
<!-- linkタグでcommon.cssファイルを読み込む -->

  <!-- タイトルの設定-->
  <title>Tutorial</title>
<body>
{% block content %}

   <!-- block content ～ endblockの間に子テンプレートの内容が差し込まれる -->

{% endblock %}

<!-- bootstrapのjavascrit読み込み-->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
</body>
</html>

pix2code/app1/templates/app1/complete.html
<!-- 親テンプレートを読み込む-->
{% extends './base.html' %}
{% load static %}
{% block content %}
<div class="content-wrapper">
<div class="container-fluid">
<div class="card mb-3">
<div class="card-header">
<h2><b>Upload Completed!</b></h2></div>
<div class="card-body">
<div class="mt-5 text-center">
<div class="alert alert-primary alert-dismissible" role="alert">
<h3 class=""><b>Upload Completed!</b></h3>
<hr>
<div class="mt-5 text-center">
    {% if message %}
   
    <h4>{{message}}<br> </h4>
  
    {% endif %}

</div>

<div class="card-body">

        
        <label>
          <a href="http://127.0.0.1:8000/media/html/{{PREDICTED_HTML}}">{{PREDICTED_HTML}}</a>
        </label>
        <br> 
     


</div>
</div>
{% if err_message %}<hr>
<div class="alert alert-danger alert-dismissible" role="alert">
    <p>Error Occured!!</p><br>
    <p>{{err_args}}</p>
    <p>{{err_message}}</p>
</div>
{% endif %}


<a class="btn btn-lg btn-secondary"  href="{% url 'app1:upload' %}">戻る</a>
</div>
</div>
</div>
</div>
</div>
</div>
{% endblock content %}

pix2code/app1/templates/app1/model_form_upload.html
<!-- 親テンプレートを読み込む-->
{% extends './base.html' %}
{% load static %}
{% block content %}
<div class="content-wrapper">
<div class="container-fluid">
<div class="mt-5 text-center">
<div class="alert alert-primary alert-dismissible" role="alert">
<p style="margin-bottom:1em;"><h3><b>ScreenShot To Html</b></h3></p>
<hr>
<h4>
<ol>

</ol>
</h4>
</div>
</div>
<hr>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
   

    {% for field in form %}
    <div class="form-group">
        {{ field.label_tag }}
        {{ field }}

        {% if field.help_text %}
            <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}

        {% if field.errors %}
        <hr>
        {% for error in field.errors %}
        <div class="alert alert-danger alert-dismissible" role="alert">
            <p>Only png format is supported.</p>
        </div>
        {% endfor %}
        {% endif %}
    </div>
{% endfor %}


    <hr>
    <button type="submit" class="btn btn-lg btn-primary">Upload</button>
    
</form>

</div>
</div>
{% endblock content %}